name: Python Package using Conda

on:
  push:
    branches:
      - main

jobs:
  build-publish:
    name: Publish Python 3 distributions 📦 to PyPI
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - name: Publish distribution 📦 to PyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: lthoangg/shopee-crawler@main
      with:
        username: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
