name: Python Package using Conda

on:
  push:
    branches:
      - main

jobs:
  build-publish:
    name: Publish Python 3 distributions 📦 to PyPI
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - name: Build binary wheel and a source tarball
      run: python setup.py sdist
    - name: Publish package
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        packages_dir: dist/
